---
swagger: "2.0"
info:
  description: "API for LargeDevProject, pushing to git, file in correct location"
  version: "1.0.2"
  title: "CloudServicesAPI"
basePath: "/api"
schemes:
- "http"
consumes:
- "application/json"
produces:
- "application/json"
paths:
  /buidlings/{buildingID}/robots/:
    get:
      tags:
      - "byBuilding"
      description: "get all robots in a specified building"
      operationId: "controllers.default_controller.buidlings_building_id_robots_get"
      parameters:
      - name: "buildingID"
        in: "path"
        description: "id for specific building"
        required: true
        type: "string"
      responses:
        200:
          description: "robots in the building"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/robot"
        default:
          description: "not found"
          schema:
            $ref: "#/definitions/errorModel"
      x-tags:
      - tag: "byBuilding"
    post:
      tags:
      - "byBuilding"
      description: "add a robot to the specified building"
      operationId: "controllers.default_controller.buidlings_building_id_robots_post"
      parameters:
      - name: "buildingID"
        in: "path"
        description: "id for specific building"
        required: true
        type: "string"
      responses:
        200:
          description: "the newly created robot"
          schema:
            $ref: "#/definitions/robot"
        default:
          description: "not found"
          schema:
            $ref: "#/definitions/errorModel"
      x-tags:
      - tag: "byBuilding"
    delete:
      tags:
      - "byBuilding"
      description: "delete all robots from building"
      operationId: "controllers.default_controller.buidlings_building_id_robots_delete"
      parameters:
      - name: "buildingID"
        in: "path"
        description: "id for specific building"
        required: true
        type: "string"
      responses:
        200:
          description: "success message"
          schema:
            type: "string"
        default:
          description: "not found"
          schema:
            $ref: "#/definitions/errorModel"
      x-tags:
      - tag: "byBuilding"
  /buidlings/{buildingID}/sensors/:
    get:
      tags:
      - "byBuilding"
      description: "get all sensors in a specific building"
      operationId: "controllers.default_controller.buidlings_building_id_sensors_get"
      parameters:
      - name: "buildingID"
        in: "path"
        description: "id for specific building"
        required: true
        type: "string"
      responses:
        200:
          description: "sensors in the building"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/sensor"
        default:
          description: "not found"
          schema:
            $ref: "#/definitions/errorModel"
      x-tags:
      - tag: "byBuilding"
    post:
      tags:
      - "byBuilding"
      description: "add a sensor to the specific building"
      operationId: "controllers.default_controller.buidlings_building_id_sensors_post"
      parameters:
      - name: "buildingID"
        in: "path"
        description: "id for specific building"
        required: true
        type: "string"
      responses:
        200:
          description: "newly created sensor"
          schema:
            $ref: "#/definitions/sensor"
        default:
          description: "not found"
          schema:
            $ref: "#/definitions/errorModel"
      x-tags:
      - tag: "byBuilding"
    delete:
      tags:
      - "byBuilding"
      description: "delete a specific user"
      operationId: "controllers.default_controller.buidlings_building_id_sensors_delete"
      parameters:
      - name: "buildingID"
        in: "path"
        description: "id for specific user"
        required: true
        type: "string"
      responses:
        200:
          description: "success message"
          schema:
            type: "string"
        default:
          description: "not found"
          schema:
            $ref: "#/definitions/errorModel"
      x-tags:
      - tag: "byBuilding"
  /robots/:
    get:
      tags:
      - "byType"
      description: "Get a list of all robots"
      operationId: "controllers.default_controller.robots_get"
      parameters: []
      responses:
        200:
          description: "array of robots in the database"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/robot"
        default:
          description: "not found"
          schema:
            $ref: "#/definitions/errorModel"
      x-tags:
      - tag: "byType"
    delete:
      tags:
      - "byType"
      description: "delete all robots"
      operationId: "controllers.default_controller.robots_delete"
      parameters: []
      responses:
        200:
          description: "success message"
          schema:
            type: "string"
        default:
          description: "not found"
          schema:
            $ref: "#/definitions/errorModel"
      x-tags:
      - tag: "byType"
  /robots/{robotID}:
    get:
      tags:
      - "byID"
      description: "return a specefic robot"
      operationId: "controllers.default_controller.robots_robot_id_get"
      parameters:
      - name: "robotID"
        in: "path"
        description: "id for specefic robot"
        required: true
        type: "string"
      responses:
        200:
          description: "robot in the database"
          schema:
            $ref: "#/definitions/robot"
        default:
          description: "not found"
          schema:
            $ref: "#/definitions/errorModel"
      x-tags:
      - tag: "byID"
    put:
      tags:
      - "byID"
      description: "update a specific robot"
      operationId: "controllers.default_controller.robots_robot_id_put"
      parameters:
      - name: "robotID"
        in: "path"
        description: "id for specific building"
        required: true
        type: "string"
      - in: "body"
        name: "newRobot"
        description: "the new data for the robot"
        required: true
        schema:
          $ref: "#/definitions/robot"
      responses:
        200:
          description: "success message"
          schema:
            type: "string"
        default:
          description: "not found"
          schema:
            $ref: "#/definitions/errorModel"
      x-tags:
      - tag: "byID"
    delete:
      tags:
      - "byID"
      description: "delete specefic robot"
      operationId: "controllers.default_controller.robots_robot_id_delete"
      parameters:
      - name: "robotID"
        in: "path"
        description: "id for specefic robot"
        required: true
        type: "string"
      responses:
        200:
          description: "success message"
          schema:
            type: "string"
        default:
          description: "not found"
          schema:
            $ref: "#/definitions/errorModel"
      x-tags:
      - tag: "byID"
  /sensors/:
    get:
      tags:
      - "byType"
      description: "get a list of all sensors"
      operationId: "controllers.default_controller.sensors_get"
      parameters: []
      responses:
        200:
          description: "array of sensors in the database"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/sensor"
        default:
          description: "not found"
          schema:
            $ref: "#/definitions/errorModel"
      x-tags:
      - tag: "byType"
    post:
      tags:
      - "byType"
      description: "create a new sensor without an associated building"
      operationId: "controllers.default_controller.sensors_post"
      parameters: []
      responses:
        200:
          description: "newly created sensor"
          schema:
            $ref: "#/definitions/sensor"
        default:
          description: "not found"
          schema:
            $ref: "#/definitions/errorModel"
      x-tags:
      - tag: "byType"
    delete:
      tags:
      - "byType"
      description: "delete all users regardless of their building"
      operationId: "controllers.default_controller.sensors_delete"
      parameters: []
      responses:
        200:
          description: "success message"
          schema:
            type: "string"
        default:
          description: "not found"
          schema:
            $ref: "#/definitions/errorModel"
      x-tags:
      - tag: "byType"
  /sensors/{sensorID}:
    get:
      tags:
      - "byID"
      description: "get a specific sensor"
      operationId: "controllers.default_controller.sensors_sensor_id_get"
      parameters:
      - name: "sensorID"
        in: "path"
        description: "id for specific sensor"
        required: true
        type: "string"
      responses:
        200:
          description: "the specific sensor"
          schema:
            $ref: "#/definitions/sensor"
        default:
          description: "not found"
          schema:
            $ref: "#/definitions/errorModel"
      x-tags:
      - tag: "byID"
    put:
      tags:
      - "byID"
      description: "update a specific sensor"
      operationId: "controllers.default_controller.sensors_sensor_id_put"
      parameters:
      - name: "sensorID"
        in: "path"
        description: "id for specific sensor"
        required: true
        type: "string"
      - in: "body"
        name: "newSensor"
        description: "the new data for the sensor"
        required: true
        schema:
          $ref: "#/definitions/sensor"
      responses:
        200:
          description: "success message"
          schema:
            type: "string"
        default:
          description: "not found"
          schema:
            $ref: "#/definitions/errorModel"
      x-tags:
      - tag: "byID"
    delete:
      tags:
      - "byID"
      description: "delete a specific sensor"
      operationId: "controllers.default_controller.sensors_sensor_id_delete"
      parameters:
      - name: "sensorID"
        in: "path"
        description: "id for specific user"
        required: true
        type: "string"
      responses:
        200:
          description: "success message"
          schema:
            type: "string"
        default:
          description: "not found"
          schema:
            $ref: "#/definitions/errorModel"
      x-tags:
      - tag: "byID"
  /users/:
    get:
      tags:
      - "byType"
      description: "get a list of users"
      operationId: "controllers.default_controller.users_get"
      parameters: []
      responses:
        200:
          description: "array of users in the database"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/user"
        default:
          description: "not found"
          schema:
            $ref: "#/definitions/errorModel"
      x-tags:
      - tag: "byType"
    post:
      tags:
      - "byType"
      description: "create a new user and returns it"
      operationId: "controllers.default_controller.users_post"
      parameters: []
      responses:
        200:
          description: "the created user"
          schema:
            $ref: "#/definitions/user"
        default:
          description: "not found"
          schema:
            $ref: "#/definitions/errorModel"
      x-tags:
      - tag: "byType"
    delete:
      tags:
      - "byType"
      description: "delete all users"
      operationId: "controllers.default_controller.users_delete"
      parameters: []
      responses:
        200:
          description: "success message"
          schema:
            type: "string"
        default:
          description: "not found"
          schema:
            $ref: "#/definitions/errorModel"
      x-tags:
      - tag: "byType"
  /users/{userID}:
    get:
      tags:
      - "byID"
      summary: "this allows api clients to get information on a specific user"
      description: "get a specific user"
      operationId: "controllers.default_controller.users_user_id_get"
      parameters:
      - name: "userID"
        in: "path"
        description: "id for specific user"
        required: true
        type: "string"
      responses:
        200:
          description: "user in the database"
          schema:
            $ref: "#/definitions/user"
        default:
          description: "not found"
          schema:
            $ref: "#/definitions/errorModel"
      x-tags:
      - tag: "byID"
    put:
      tags:
      - "byID"
      description: "update a specific user"
      operationId: "controllers.default_controller.users_user_id_put"
      parameters:
      - name: "userID"
        in: "path"
        description: "id for specific user"
        required: true
        type: "string"
      - in: "body"
        name: "newUser"
        description: "the new data for the user"
        required: true
        schema:
          $ref: "#/definitions/user"
      responses:
        200:
          description: "success message"
          schema:
            type: "string"
        default:
          description: "not found"
          schema:
            $ref: "#/definitions/errorModel"
      x-tags:
      - tag: "byID"
    delete:
      tags:
      - "byID"
      description: "delete a specific user"
      operationId: "controllers.default_controller.users_user_id_delete"
      parameters:
      - name: "userID"
        in: "path"
        description: "id for specific user"
        required: true
        type: "string"
      responses:
        200:
          description: "success message"
          schema:
            type: "string"
        default:
          description: "not found"
          schema:
            $ref: "#/definitions/errorModel"
      x-tags:
      - tag: "byID"
definitions:
  sensor:
    type: "object"
    properties:
      id:
        type: "string"
      buildingID:
        type: "string"
      floor:
        type: "number"
        format: "int"
      room:
        type: "number"
        format: "int"
      xpos:
        type: "number"
        format: "int"
      ypos:
        type: "number"
        format: "int"
      robot:
        type: "string"
      from:
        type: "string"
      type:
        type: "string"
  user:
    type: "object"
    properties:
      id:
        type: "string"
      buildingID:
        type: "string"
      floor:
        type: "number"
        format: "int"
      room:
        type: "number"
        format: "int"
      xpos:
        type: "number"
        format: "int"
      ypos:
        type: "number"
        format: "int"
      message:
        type: "string"
      owner:
        type: "boolean"
  errorModel:
    type: "object"
    required:
    - "message"
    properties:
      message:
        type: "string"
  robot:
    type: "object"
    properties:
      id:
        type: "string"
      buildingID:
        type: "string"
      sensorID:
        type: "array"
        items:
          type: "string"
      capabilities:
        type: "array"
        items:
          type: "string"
      movement:
        type: "string"
      floor:
        type: "number"
        format: "int"
      room:
        type: "number"
        format: "int"
      xpos:
        type: "number"
        format: "int"
      ypos:
        type: "number"
        format: "int"
      from:
        type: "string"
